{
 "title": "New dashboard Copy",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Telegraf",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_display_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "display_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_services",
     "select": [
      [
       { "params": [ "startup_mode" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "display_name",
       "operator": "=",
       "value": "Telegraf Data Collector Service"
      }
     ]
    }
   ]
  },
  {
   "title": "Influxdb",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_display_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "display_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_services",
     "select": [
      [
       { "params": [ "startup_mode" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=", "value": "influxdb_3" }
     ]
    }
   ]
  },
  {
   "title": "Grafana",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_display_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "display_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_services",
     "select": [
      [
       { "params": [ "startup_mode" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=", "value": "graphana_v4" }
     ]
    }
   ]
  },
  {
   "title": "Proccesor",
   "type": "graph",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$col $tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "win_system",
     "select": [
      [
       { "params": [ "Processor_Queue_Length" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$col $tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "win_net",
     "select": [
      [
       { "params": [ "Bytes_Total_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Bytes Total/sec" ], "type": "alias" }
      ],
      [
       { "params": [ "Bytes_Received_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Bytes Received/sec" ], "type": "alias" }
      ],
      [
       { "params": [ "Bytes_Sent_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Bytes Sent/sec" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Physical Disk",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$col $tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "win_diskio",
     "select": [
      [
       { "params": [ "Avg._Disk_sec/Read" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Averege Disk secs/Read" ], "type": "alias" }
      ],
      [
       { "params": [ "Avg._Disk_sec/Write" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Averege Disk secs/Write" ], "type": "alias" }
      ],
      [
       { "params": [ "Avg._Disk_Queue_Length" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Averege Disk Queue Length" ], "type": "alias" }
      ],
      [
       { "params": [ "Current_Disk_Queue_Length" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Current Disk Queue Length" ], "type": "alias" }
      ],
      [
       { "params": [ "Percent_Disk_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "%  Disk Time" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$col $tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_mem",
     "select": [
      [
       { "params": [ "Available_Bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Available_Bytes" ], "type": "alias" }
      ],
      [
       { "params": [ "Percent_Committed_Bytes_In_Use" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "% Committed Bytes In Use" ], "type": "alias" }
      ],
      [
       { "params": [ "Page_Faults_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Page Faults/sec" ], "type": "alias" }
      ],
      [
       { "params": [ "Pages_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Pages/sec" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Processor",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$col $tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "win_cpu",
     "query": "SELECT mean(\"Percent_Processor_Time\") AS \"% Process Time\", mean(\"Percent_User_Time\") AS \"% User Time\" FROM \"win_cpu\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "Percent_Processor_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "% Process Time" ], "type": "alias" }
      ],
      [
       { "params": [ "Percent_User_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "% User Time" ], "type": "alias" }
      ],
      [
       { "params": [ "Percent_Idle_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "% Idle Time" ], "type": "alias" }
      ],
      [
       { "params": [ "Percent_Interrupt_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "% Interrupt Time" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}